[versions]
agp = "9.1.1"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"
androidx-activityCompose = "1.13.0"
componentsResources = "1.12.0"
compose = "1.12.0"
compose-plugin = "1.12.0"
constraintlayoutComposeMultiplatform = "0.8.2"
foundation = "1.12.0"
kotlin = "2.4.20"
lifecycleViewmodelCompose = "2.11.0"
material3 = "1.9.0"
materialIconsExtended = "1.7.3"
materialKolor = "5.0.1"
runtime = "1.12.0"
ui = "1.12.0"

[libraries]
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
constraintlayout-compose-multiplatform = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "constraintlayoutComposeMultiplatform" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
